main: com.github.oobila.bukkit.CorePlugin
name: ABCore
version: '1.9-SNAPSHOT'
description: This is a library plugin.
author: oobila
website: 'https://github.com/oobila/ab-core'
api-version: 1.16
softdepend:
  - Vault
  - WorldEdit
  - ABPresent
  - ABSkyLantern
  - ABEnderPlots
  - ABPlunderers
commands:
permissions: